// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC9CeFybEt__r3CNqg82OqGR1kT5p001s',
    appId: '1:106046947896:android:2dac98b96695a0b6c21ccd',
    messagingSenderId: '106046947896',
    projectId: 'connfy-aa8f8',
    storageBucket: 'connfy-aa8f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALyL2niAkf9iOA142AcHverJp-iUmUXaU',
    appId: '1:106046947896:ios:c73bad2d778c3e05c21ccd',
    messagingSenderId: '106046947896',
    projectId: 'connfy-aa8f8',
    storageBucket: 'connfy-aa8f8.appspot.com',
    iosBundleId: 'com.slice.connfy',
  );

/*
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvikoV4rYnmAGDXK469-vR7aGggATdNF',
    appId: '1:1034760404757:android:8215a270e1baf2c18c331c',
    messagingSenderId: '1034760404757',
    projectId: 'newconnfy',
    storageBucket: 'newconnfy.appspot.com',
  );
*/
}
